#!/usr/bin/env bash

for file in examples/*.cl; do
	./cool_lexer ${file} > ${file}.txt
	if diff ${file}.out ${file}.txt > /dev/null 2>&1; then
		echo ${file} "--> PASSED"
		rm ${file}.txt
	else
		echo ${file} "--> FAILED"
		diff ${file}.out ${file}.txt
	fi
done
